### ISSUE TITLE
Add support for metric alerts

### ISSUE THREAD

**Issue by larosek** [jianyuan/terraform-provider-sentry#102]
Hi! First I want to say thank you for making this Terraform provider!

Would it be possible to add support for metric alerts. This new alert type does not use the same schema as the issue alerts currently supported by the provider.

https://docs.sentry.io/product/alerts/alert-types/#metric-alerts
https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/

Thanks!

**Comment by javaadsnappcar** [comment]
Is there any plan to add this functionality?

**Comment by javaadsnappcar** [comment]
I've started trying to add this functionality, starting with this PR to update the go client:
https://github.com/jianyuan/go-sentry/pull/25

After that I will try to add support for APM alerts.

**Comment by javaadsnappcar** [comment]
I opened this PR: https://github.com/jianyuan/terraform-provider-sentry/pull/120 to support APM alerts, waiting for feedback.

**Comment by jianyuan** [comment]
Thank you for your contribution! [This will be available in the upcoming release](https://github.com/jianyuan/terraform-provider-sentry/blob/main/docs/resources/metric_alert.md).
