### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by mwarkentin** [jianyuan/terraform-provider-sentry#11]
Hey, not sure if you're still working on this, but I was interested in trying it out.

It'd be helpful if there were some installation instructions to help get it set up (not very familiar w/ terraform plugins).

I've used [another](https://github.com/mattaitchison/terraform-provider-convox#install) which provided a simple `make install` command, however a set of commands to run would be fine as well.

Thanks for your work on this!

**Comment by mwarkentin** [comment]
Actually, this worked for me and was pretty simple:

```
go get github.com/jianyuan/terraform-provider-sentry
cd ~/go/src/github.com/jianyuan/terraform-provider-sentry
go build
cp terraform-provider-sentry ~/.terraform.d/plugins/
```

**Comment by jianyuan** [comment]
@mwarkentin The official way of installing third-party plugins is now with the command `terraform init`.

**Comment by Quantisan** [comment]
I tried `terraform init` and it threw an error (see below). Then I followed @mwarkentin's instruction to build the binary, copy into `~/.terraform.d/plugins/`, and that actually worked.

```
Provider "sentry" not available for installation.

A provider named "sentry" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
```

**Comment by jianyuan** [comment]
The official instructions can be found here: https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

I will update our README about this.

**Comment by jianyuan** [comment]
Readme updated.
