### ISSUE TITLE
Alternate means of providing the token

### ISSUE THREAD

**Issue by syphernl** [jianyuan/terraform-provider-sentry#110]
Currently the `token` can be provided by creating a provider instance with `token` argument or an environment variable `SENTRY_TOKEN`. 
It would be nice if this provider could also read from the tfenv.

This would be similar to that of the [Gitlab Provider](https://github.com/gitlabhq/terraform-provider-gitlab) where we can simply put this into `terraform.tfvars`:
```
gitlab_token = "xxxx"
```
and it gets automatically picked up by the provider. No need to explicitly create a `provider "gitlab" {... }` entry or provide an environment variable.

I have tried the same with adding the following to `terraform.tfvars`:
```
sentry_token = "xxxx"
```

However, it does not work and errors out:
```
│ Error: Missing required argument
│ 
│ The argument "token" is required, but was not set.
╵
```

Is this something that can be implemented?

**Comment by jianyuan** [comment]
Hi @syphernl, I'm not exactly sure how that works. The examples in that provider do have the `provider "gitlab" { ... }` block. Are you sure `GITLAB_TOKEN` is not set prior to running `terraform`?

**Comment by syphernl** [comment]
You are right! 
I am indeed (also) setting `GITLAB_TOKEN` prior to running `terraform`. Not sure why we then need that `tfvars` entry then 😅 .. 
With `SENTRY_TOKEN` as env variable it seems to be working just fine.
