### ISSUE TITLE
No darwin_arm64 build available from terraform registry

### ISSUE THREAD

**Issue by k321rf** [jianyuan/terraform-provider-sentry#112]
Terraform Version

v1.1.4
Affected Resource(s)

N/A

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
Terraform Configuration Files

N/A
Debug Output

Error: Incompatible provider version

Provider registry.terraform.io/jianyuan/sentry v0.6.0 does not have a package available for your current platform, darwin_arm64.

Expected Behavior

A binary for `darwin_arm64` is available from Terraform registry
Actual Behavior

Terraform fails with above mentioned error
Steps to Reproduce

On a Macbook Pro M1 with a plan requiring the sentry provider:

    terraform init

**Comment by jianyuan** [comment]
Hi @k321rf, [darwin_arm64 support is only available from v0.7.0 onwards](https://github.com/jianyuan/terraform-provider-sentry/releases/tag/v0.7.0).

**Comment by k321rf** [comment]
Yes then this issue can be closed. The version 0.7.0 for darwin arm64 architecture works.

Thanks for the hint
