### ISSUE TITLE
Error on apply

### ISSUE THREAD

**Issue by mwarkentin** [jianyuan/terraform-provider-sentry#16]
Sorry about flooding you with issues right now - just ran across something else I haven't seen before.

I've imported a sentry project, and am now trying to do an apply to change the name to follow our convention. It's giving me an error that doesn't really indicate what the problem actually is, and I'm not sure how to figure out what might be going wrong. I've done similar changes to other projects without issue previously.

### Plan

```
  ~ module.sentry_project.sentry_project.default
      slug: "prod-payments-web-4e" => "prod-payments-web"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Error

```
$ make apply app=payments-web
module.sentry_project.sentry_project.default: Modifying... (ID: prod-payments-web-4e)
  slug: "prod-payments-web-4e" => "prod-payments-web"
Error applying plan:

1 error(s) occurred:

* module.sentry_project.sentry_project.default: 1 error(s) occurred:

* sentry_project.default: sentry: map[detail:Internal Error errorId:56e87ac59c6d493d9040a1f3a445300c]

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by mwarkentin** [comment]
Ah, it looks like there's another project already set up that's using that slug already. Not sure if there's a way to provide a better error message or not. Happy to close this issue if you'd like.

**Comment by jianyuan** [comment]
@mwarkentin It looks like a bug with Sentry's API. I will try to replicate this and file a bug with them. It doesn't look like there's anything we can do about this issue.

**Comment by mwarkentin** [comment]
Ok, let me know if there's any more information I can provide. :)
