### ISSUE TITLE
Error: Could node find rule with ID X

### ISSUE THREAD

**Issue by dwilliams782** [jianyuan/terraform-provider-sentry#181]
Hi,

We ran into an issue lately where our Terraform state got very messed up, and it ended up with a bunch of `sentry_rule` resources that existed in state but not upstream. No different to if a user went and deleted the rule from the UI.

The `terraform plan` could no longer succeed:

![image](https://user-images.githubusercontent.com/42545485/177511872-19de1bc3-46d7-486e-b63a-73c6bd19e4fe.png)

I had to remove them from state before the plan would work. This should cause TF to re-add the missing resource rather than error.

Seen on versions `0.6.0` and `0.9.0`.

**Comment by jianyuan** [comment]
I'm going to close this since it's likely fixed in the latest version.
