### ISSUE TITLE
Feature Request: Create team if not exists

### ISSUE THREAD

**Issue by lucasteles** [jianyuan/terraform-provider-sentry#199]
Would be nice to have a way to "sentry_team" to reuse an existing team with same name/slug

**Comment by thetimbecker** [comment]
Would using the `sentry_team` data source solve your issue?

https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/data-sources/team

**Comment by jianyuan** [comment]
I agree with @thetimbecker. I'll close this for now.
