### ISSUE TITLE
Feature request: Link multiple teams to projects

### ISSUE THREAD

**Issue by mhindery** [jianyuan/terraform-provider-sentry#209]
In the Sentry UI, multiple teams can be linked to a project. In the Terraform resource on projects, only one team can be defined on it. If I have a project with multiple teams configured in Sentry, and I have that project in Terraform, it does remove all teams except from the one that can be set in the project resource. The modelling should be changed so that multiple teams can be added to a project.

**Comment by jianyuan** [comment]
This is now possible since [v0.10.0](https://github.com/jianyuan/terraform-provider-sentry/releases/tag/v0.10.0) 🎉
