### ISSUE TITLE
Validate project platforms on plan

### ISSUE THREAD

**Issue by acm19** [jianyuan/terraform-provider-sentry#213]
Currently `platform` is not validated for `sentry_project` resource. The plan will succeed and the apply will fail if an invalid platform is introduced. Only a list of attributes are valid that should be validated at `terraform plan` time.

**Comment by danielpoonwj** [comment]
AFAIK there doesn't seem to be a reliable way to get the platforms through an API or documentation. This hacky bit of JS can be used on the console of the new project page to scrape valid platforms.

```javascript
Array.from(document.querySelectorAll("div[data-test-id^='platform-']")).map((element) => {
  return element.getAttribute('data-test-id').replace(/platform-/, '');
});
```

I'm not sure how often these change, but imo hardcoding validation might cause issues in the future.

**Comment by jianyuan** [comment]
They seemed to store the complete list here:

1. https://github.com/getsentry/sentry/blob/master/src/sentry/utils/platform_categories.py
2. https://github.com/getsentry/sentry/blob/master/static/app/data/platformCategories.tsx

I don't see a way to retrieve them programmatically. Let me enquire about this with the Sentry team and revert.

**Comment by acm19** [comment]
Hardcoding it is not really bad as long as they don't provide it. Regions are hardcoded in the AWS client for example: https://github.com/hashicorp/aws-sdk-go-base/blob/main/internal/endpoints/endpoints.go and https://github.com/aws/aws-sdk-go/blob/main/models/endpoints/endpoints.json. It'd be possible to automatically generate it from Sentry code. In any case it's always possible to bump the provider if your platform is not provided. I could take a look and contribute it you'd be happy with that when I have some time.
