### ISSUE TITLE
Feature request: Issue Grouping

### ISSUE THREAD

**Issue by alyssaruth** [jianyuan/terraform-provider-sentry#230]
Hey, thanks for the provider!

My team uses Sentry, the main thing that would be valuable for us to manage via terraform are the issue grouping rules (found at https://sentry.io/settings/$ORG_SLUG/projects/$PROJECT_SLUG/issue-grouping/). Having this as something managed via source control would be really awesome!

**Comment by jianyuan** [comment]
Here is what the enhancement could look like:

```terraform
resource "sentry_project" "my_project" {

  # ...

  # FINGERPRINT RULES
  fingerprinting_rules = <<-EOT
  # force all errors of the same type to have the same fingerprint
  error.type:DatabaseUnavailable -> system-down
  # force all memory allocation errors to be grouped together
  stack.function:malloc -> memory-allocation-error
  EOT

  # STACK TRACE RULES
  grouping_enhancements = <<-EOT
  # remove all frames above a certain function from grouping
  stack.function:panic_handler ^-group
  # mark all functions following a prefix in-app
  stack.function:mylibrary_* +app
  EOT
}
```

**Comment by mtanda** [comment]
I want to use this feature.
I made a PR to support this feature, please review it :-)
https://github.com/jianyuan/go-sentry/pull/76

**Comment by ryanbratten** [comment]
Hi, I see the PR has been open for a while. I'd love to have this feature available through Terraform. We currently manage our sentry configuration entirely through Terraform except for this small part. Do we know when this might be available?
Thanks,
Ryan

**Comment by ledniov** [comment]
Hi @jianyuan , can you please review the linked PR? Our team would benefit from having this feature - we'll have full coverage of our configuration for Sentry written in Terraform.
