### ISSUE TITLE
fix: Extend the Project ID range by changing the type from int to string

### ISSUE THREAD

**Issue by NguyenHoangPhuTien** [jianyuan/terraform-provider-sentry#233]
Hey, thanks for the provider!

Currently, I need to create new metric alerts for my organization. I copied the code as an example like [this](https://registry.terraform.io/providers/jianyuan/sentry/0.9.0/docs/resources/metric_alert) and replaced some values that needed. After ran the command "terraform plan", I got the issue 

`Error: json: cannot unmarshal array into Go value of type sentry.MetricAlert
│ 
│   with sentry_metric_alert.main,
│   on alerts.tf line 67, in resource "sentry_metric_alert" "main":
│   67: resource "sentry_metric_alert" "main" `

Here are my code

`resource "sentry_metric_alert" "main" {
  organization      = "xxx"
  project           = "xxxxx"
  name              = "My metric alert"
  dataset           = "events"
  query             = ""
  aggregate         = "count()"
  time_window       = 60
  threshold_type    = 0
  resolve_threshold = 0
  trigger {
    alert_threshold = 100
    label           = "warning"
    threshold_type  = 0
  }
}`

Can you help to advice me for this case?

I am using jianyuan/sentry==0.9.0  and terrafrom==1.3.5

**Comment by jianyuan** [comment]
It seems to be related to this change: https://github.com/getsentry/sentry/pull/35643

 I think changing it to a string is sensible.

**Comment by mccorrym** [comment]
Is there a workaround available for this issue until the PR is merged? I also have 16-digit Sentry project IDs which are not compatible with the latest version of this provider. Is it possible to specify the DSN manually?
