### ISSUE TITLE
resource/sentry_metric_alert: an unexpected new value for was present, but now absent.

### ISSUE THREAD

**Issue by NguyenHoangPhuTien** [jianyuan/terraform-provider-sentry#236]
Hi @jianyuan ,

Currently, I got the error "an unexpected new value for was present, but now absent" when applying for creating a new metric alert with Slack integration. But did not get this issue when I apply without slack integration. Here are my code

`resource "sentry_metric_alert" "tien_alert" {
  organization      = "xxxxxx"
  project           = "xxxx"
  name              = "TIEN Alert"
  dataset           = "events"
  query             = ""
  aggregate         = "count()"
  time_window       = 30
  threshold_type    = 0
  resolve_threshold = 40
  environment       = "staging"

  trigger {
    action {
      type              = "slack"
      target_type       = "specific"
      target_identifier = "#test"
      integration_id    = data.sentry_organization_integration.slack.id
    }
    alert_threshold = 100000
    label           = "critical"
    threshold_type  = 0
  }
}`

I created the custom terraform plugin from main branch and got this issue. Can you help advice me on this case? Anyone have this issue like me?

**Comment by NguyenHoangPhuTien** [comment]
Here is the log from terraform command
`2022-12-08T16:08:37.170+0700 [DEBUG] provider.terraform-provider-sentry: Reading metric alert: alertID= org= project= tf_req_id=3e7b8e8f-4175-2d88-0526-0f7660b60614 @caller=/home/tienhpn/projects/terraform-provider-sentry/sentry/resource_sentry_metric_alert.go:221 @module=provider tf_provider_addr=provider tf_resource_type=sentry_metric_alert tf_rpc=ApplyResourceChange timestamp=2022-12-08T16:08:37.169+0700
2022-12-08T16:08:37.170+0700 [WARN]  unexpected data:xxxx/julo/sentry:stdout="org %!d(string=)
project %!d(string=)
alertID %!d(string=)"
2022-12-08T16:08:37.398+0700 [INFO]  provider.terraform-provider-sentry: Removing metric alert from state because it no longer exists in Sentry: tf_provider_addr=provider tf_req_id=3e7b8e8f-4175-2d88-0526-0f7660b60614 tf_resource_type=sentry_metric_alert tf_rpc=ApplyResourceChange @caller=/home/tienhpn/projects/terraform-provider-sentry/sentry/resource_sentry_metric_alert.go:253 org= @module=provider timestamp=2022-12-08T16:08:37.397+0700`

I think we can not get the project, alertID & org for reading the information when we run this function `resourceSentryMetricAlertRead`

**Comment by jianyuan** [comment]
Continue discussions in #200
