### ISSUE TITLE
Slack integration v0.10.0

### ISSUE THREAD

**Issue by jpaulgs** [jianyuan/terraform-provider-sentry#249]
Hey,

I've followed the notes on main to [retrieve details of the slack integration](https://github.com/jianyuan/terraform-provider-sentry/blob/a52cb27d27c10f4804958cc6d02a633ef6e4bc1a/docs/data-sources/organization_integration.md?plain=1#L24)

However when I attempt to run a terraform plan I get the following error 

![image](https://user-images.githubusercontent.com/30516993/208790737-e4c6c294-503f-4768-b38c-9b32c4fd59a7.png)

Seems like a similar error as #233 

So I'm starting to suspect that it isn't possible to configure slack alerts in 0.10.0 is correct?

**Comment by jpaulgs** [comment]
Actually it is possible to create an alert that pushes to slack without specifying the `sentry_organisation_integration`

The action for the alert will look something like:
```
    {
      id        = "sentry.integrations.slack.notify_action.SlackNotifyServiceAction"
      channel   = "SLACK CHANNEL"
      workspace = "REDACTED"
    }
```

To find the workspace ID you will need to navigate to `Sentry -> Settings -> Integrations -> Slack` and press the 'configurations' tab then 'configure' the url will look something like `https://sentry.io/settings/organisation/integrations/slack/1234/`. The ID number in path is the value for workspace

**Comment by pra-cloud** [comment]
Thanks @jpaulgs   for id of slack
