### ISSUE TITLE
Support retrieving the DSN for a project?

### ISSUE THREAD

**Issue by orf** [jianyuan/terraform-provider-sentry#25]
It would be handy to be able to output a projects DSN after it's been created through terraform. You can get this via the `/keys/` endpoint, under the `dsn` object.

I'm not sure how you would expose this in TF though

**Comment by jianyuan** [comment]
@orf There is a [sentry_key resource](https://github.com/jianyuan/terraform-provider-sentry/blob/25689a0f122b9a179add270a27602c92dbf83ee0/sentry/resource_sentry_key_test.go#L118-L122). It looks there is no documentation for this resource.

**Comment by bee-keeper** [comment]
`
resource "sentry_project" "default" {
    organization = "organization"
    team = "team"
    name = "name"
}

resource "sentry_key" "key" {
    organization = "${sentry_project.default.organization}"
    project = "${sentry_project.default.name}"
    name = "${sentry_project.default.name}"
}

output "sentry_dsn" {
    value = "${sentry_key.key.dsn_public}"
}
`
Here's one for the drive by copy pasters.

**Comment by SpamapS** [comment]
Looks like this one can be closed, yes?
