### ISSUE TITLE
'other' Platform Type No Longer Supported?

### ISSUE THREAD

**Issue by Raynbag** [jianyuan/terraform-provider-sentry#261]
With the recent changes to the way that project platform types are validated I'm receiving the following error back when running terraform plan.

'Error: other is not a valid platform'

Looking in the Sentry UI I can see that 'Other' is still an option when creating/updating a project. Is this something that could be fixed or are Sentry planning on removing this as a platform type in the future?

Many thanks in advance.

**Comment by jianyuan** [comment]
Thanks for reporting! This will be fixed in the next patch release.

**Comment by Raynbag** [comment]
@jianyuan Amazing, thank you so much!
