### ISSUE TITLE
Add support of `inputChannelId` on `sentry_metric_alert`

### ISSUE THREAD

**Issue by geototti21** [jianyuan/terraform-provider-sentry#281]
👋 Hey

I am trying to create a new `sentry_metric_alert` that has as action a Slack alert. 

It is failing with ` getting the status of the metric alert creation from Sentry took too long`, and I believe it is because of the rate limits from [Slack](https://docs.sentry.io/product/integrations/notification-incidents/slack/#rate-limiting-error). Docs say to also pass the  Slack channelID to avoid that.

I can see that `inputChannelId` is already specified on the [go-sentry](https://github.com/jianyuan/go-sentry/blob/main/sentry/metric_alerts.go#L59) client, so I believe we need to expose this from the terraform provider as well so it will look like this:

```terraform
  trigger {
    action {
      type              = "slack"
      target_type       = "specific"
      target_identifier = "#alert-channel"
      # new field needed below
      input_channel_id  = "C0XXXXXXXXX"
      integration_id    = data.sentry_organization_integration.slack.id
    }
    alert_threshold = 300
    label           = "critical"
    threshold_type  = 0
  }
```
Please let me know what you think. 😄

**Comment by jianyuan** [comment]
The `input_channel_id` is now available in [v0.12.0](https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/metric_alert#input_channel_id)!
