### ISSUE TITLE
Add support to show tags to Slack notification in alerts

### ISSUE THREAD

**Issue by Paszymaja** [jianyuan/terraform-provider-sentry#284]
Hi,

At the time of writing, it is possible to add the tags to the Slack notification in the alerts tab.
![image](https://user-images.githubusercontent.com/36695377/221535038-19fb2ab8-33f9-41b1-84cd-441e99c6513b.png)

It is not possible to add them using terraform provider.

Is this feature on your roadmap?
If not could you point me to where, in the provider, changes must be made to enable it?

**Comment by MarcDufresne** [comment]
I was able to make this work by passing `tags`, like so:
```
{
      id = "sentry.integrations.slack.notify_action.SlackNotifyServiceAction"
      channel = var.slack_high_priority_channel
      workspace = data.sentry_organization_integration.slack.internal_id
      tags = "environment"  # <--- This should work the same as in the Sentry UI, so comma-separated values
},
```

**Comment by jianyuan** [comment]
I have updated the example to reflect this.
