### ISSUE TITLE
Version compatablity 

### ISSUE THREAD

**Issue by bumarcell** [jianyuan/terraform-provider-sentry#308]
Hi, hope you're doing well!

I just started using Terraform particularly for managing Sentry 'configurations'. My plan is to manage Sentry config data like projects, teams, members etc. and have it saved in code.
Currently we have self-hosted Sentry version 22.11.0 in production, which isn't the latest. to upgrade Sentry major version I will have to migrate the aforementioned data somehow, which I'm planing to do with Terraform 💡 

Unfortunately my first `terraform import` test has crashed and I'm suspecting a version incompatibility between the provider and Sentry. Is there a particular provider version I should use with Sentry version 22.11.0?

Here's the crash report:
``terraform` import sentry_organization.main main

sentry_organization.main: Importing from ID "main"...
sentry_organization.main: Import prepared!
  Prepared sentry_organization for import
sentry_organization.main: Refreshing state... [id=main]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-sentry_v0.11.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x16bd669]

goroutine 37 [running]:
github.com/jianyuan/go-sentry/v2/sentry.CheckResponse(0x17b46e0?)
	github.com/jianyuan/go-sentry/v2@v2.2.0/sentry/sentry.go:343 +0x29
github.com/jianyuan/terraform-provider-sentry/sentry.(*Config).Client.func1(0x198d910?, 0xc00012c008?, 0x15?, 0x1989500?)
	github.com/jianyuan/terraform-provider-sentry/sentry/config.go:39 +0x30
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000268150, 0xc00080a690)
	github.com/hashicorp/go-retryablehttp@v0.7.2/client.go:680 +0xd37
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc000427230, 0x0?)
	github.com/hashicorp/go-retryablehttp@v0.7.2/roundtripper.go:44 +0x7d
github.com/jianyuan/terraform-provider-sentry/sentry.(*semaphoreTransport).RoundTrip(0xc0002b7050, 0xc000270100)
	github.com/jianyuan/terraform-provider-sentry/sentry/config.go:83 +0x20f
net/http.send(0xc000270100, {0x1988240, 0xc0002b7050}, {0x18421e0?, 0x1016e01?, 0x0?})
	net/http/client.go:251 +0x5f7
net/http.(*Client).send(0xc0002b7080, 0xc000270100, {0xc0001bcbf8?, 0x1019866?, 0x0?})
	net/http/client.go:175 +0x9b
net/http.(*Client).do(0xc0002b7080, 0xc000270100)
	net/http/client.go:715 +0x8fc
net/http.(*Client).Do(...)
	net/http/client.go:581
github.com/jianyuan/go-sentry/v2/sentry.(*Client).BareDo(0x0?, {0x198d948, 0xc000592480}, 0xc00058a200?)
	github.com/jianyuan/go-sentry/v2@v2.2.0/sentry/sentry.go:242 +0x45
github.com/jianyuan/go-sentry/v2/sentry.(*Client).Do(0xc00034c460?, {0x198d948?, 0xc000592480?}, 0xc000598240?, {0x172c460?, 0xc0005dc2c0})
	github.com/jianyuan/go-sentry/v2@v2.2.0/sentry/sentry.go:260 +0x79
github.com/jianyuan/go-sentry/v2/sentry.(*OrganizationsService).Get(0xc00034c480, {0x198d948, 0xc000592480}, {0xc000582180?, 0xc0005e6fd8?})
	github.com/jianyuan/go-sentry/v2@v2.2.0/sentry/organizations.go:108 +0xe5
github.com/jianyuan/terraform-provider-sentry/sentry.resourceSentryOrganizationRead({0x198d948, 0xc000592480}, 0xc0005ee580, {0x179f140?, 0xc00034c460})
	github.com/jianyuan/terraform-provider-sentry/sentry/resource_sentry_organization.go:78 +0x27e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000249420, {0x198d980, 0xc0005d2ae0}, 0xd?, {0x179f140, 0xc00034c460})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000249420, {0x198d980, 0xc0005d2ae0}, 0xc0005f6410, {0x179f140, 0xc00034c460})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000427e48, {0x198d980?, 0xc0005d29c0?}, 0xc00012a880)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00034d540, {0x198d980?, 0xc0005d21b0?}, 0xc000592120)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x182ddc0?, 0xc00034d540}, {0x198d980, 0xc0005d21b0}, 0xc000342690, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001de1e0, {0x1991400, 0xc000007ba0}, 0xc0005da000, 0xc00043baa0, 0x1e2c250, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001de1e0, {0x1991400, 0xc000007ba0}, 0xc0005da000, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-sentry_v0.11.2 plugin crashed!`

**Comment by ztzxt** [comment]
We were getting the similar trace log with Sentry version `23.4.0`. Our Sentry was down when the terraform commands are run. Errors were resolved after having it up again. Maybe the module could be more verbose and throw an error about not being able to reach to Sentry.

**Comment by bumarcell** [comment]
That was the problem actually
