### ISSUE TITLE
Terraform module registry complains: "This module version (0.4.0) has no root configuration. A module with no root configuration cannot be used directly."

### ISSUE THREAD

**Issue by boldandbusted** [jianyuan/terraform-provider-sentry#31]
What it says on the tin. It would be lovely to see this provider level up in the Registry. :) Link: https://registry.terraform.io/modules/jianyuan/sentry/provider/0.4.0. Cheers!

**Comment by jleclanche** [comment]
What are the implications of this? It can't be installed from terraform init?

**Comment by jianyuan** [comment]
I think the error message only applies to Terraform modules, not Terraform providers.

**Comment by mwarkentin** [comment]
Is this installable from the registry now? Are there instructions for how you do this?

**Comment by taiidani** [comment]
A little confused on this myself. This is a Sentry provider, not a module yah? It looks like that's in the TF Module Registry as a module.

![image](https://user-images.githubusercontent.com/902500/57561188-29a00e80-733f-11e9-9654-4c13c42db93a.png)

I could be wrong, but unless this is part of the process to register this as an official provider it feels like it may be in the wrong place.

**Comment by jianyuan** [comment]
[This provider is now available via their Terraform's official registry :tada:](https://registry.terraform.io/providers/jianyuan/sentry/latest).
