### ISSUE TITLE
Support not creating default alerts when creating a project

### ISSUE THREAD

**Issue by pksunkara** [jianyuan/terraform-provider-sentry#313]
When creating a project, sentry API has `default_rules` that can be set to `false`, and when done so will not create any alerts by default.

Can you please add support for that in `sentry_project` resource?

I don't mind contributing a PR, but please let me know if this is something that you would accept.

Thanks.

**Comment by jianyuan** [comment]
The `default_rules` parameter is now available in [v0.12.0](https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/project#default_rules).
