### ISSUE TITLE
Sentry Terraform provider does not recognize "React" as a valid platform

### ISSUE THREAD

**Issue by vodila-privet** [jianyuan/terraform-provider-sentry#314]
Hello,

I'm working with the Sentry Terraform provider and I've encountered a problem when attempting to set "React" as a platform for a Sentry project.

Here is a sample of my Terraform configuration:
```
resource "sentry_project" "default" {
  // Other settings omitted for brevity
  platform = "react"
}
```

When I run this, it results in an error stating that "react" is not a valid platform. After investigating, I found the validation process within the provider uses a certain mechanism to verify the platform. It forms URLs and tries to reach them, assuming if the URL is reachable, then the platform is valid.

Here's the validation function for reference - https://github.com/jianyuan/terraform-provider-sentry/blob/main/sentry/resource_sentry_project.go#L359

The issue is that for some platforms, like React, the documentation URL includes additional segments (e.g., https://docs.sentry.io/platforms/javascript/guides/react/), which the current validation function doesn't account for. As a result, "react" is not recognized as a valid platform despite being officially supported, according to Sentry's documentation.

Could a workaround exist to define React as the platform in my current Terraform setup? Or could the validation function be updated to accommodate the structure of URLs like the one for React?

Your guidance would be greatly appreciated.

Thank you.

Similar issues:
https://github.com/jianyuan/terraform-provider-sentry/issues/288
https://github.com/jianyuan/terraform-provider-sentry/issues/297

**Comment by dteoh** [comment]
I wonder if we can just drop the need to validate this and instead link to the list of values that Sentry will accept?

**Comment by jianyuan** [comment]
FWIW, the full list of platforms is available here: https://github.com/getsentry/sentry/blob/master/src/sentry/utils/platform_categories.py

@vodila-privet For react, the platform should be `javascript-react`.

**Comment by dteoh** [comment]
Thanks for the list! That worked for us.

**Comment by vodila-privet** [comment]
Thanks!!!
