### ISSUE TITLE
sentry_issue_alert action block - pagerduty service support

### ISSUE THREAD

**Issue by rajesh-dhakad** [jianyuan/terraform-provider-sentry#320]
For the "sentry_issue_alert" resource - how we can get the service id using the data source or any other way as the action block doesn't support service name.

`│ Error: PUT https://sentry.io/api/0/projects/apolloio/staging/rules/14621324/: 400 map[actions:[Select a valid choice. Intelligence is not one of the available choices.]]`

```
  actions = [
    {
      id = "sentry.integrations.pagerduty.notify_action.PagerDutyNotifyServiceAction"
      name = "Send a notification to PagerDuty account <account> and service <service>"
      account = data.sentry_organization_integration.pagerduty.id
      service = "Intelligence"
    }
  ]
```
  
I came across this but don't think this is the right way to do for terraform - https://github.com/jianyuan/terraform-provider-sentry/issues/87#issuecomment-959518109

**Comment by jianyuan** [comment]
[Sentry has an official documentation for this now](https://docs.sentry.io/api/alerts/create-an-issue-alert-rule-for-a-project/). Unfortunately, it's not very clear where the values come from. I will create some examples of how to configure this.

**Comment by jianyuan** [comment]
I have added an example here: https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/issue_alert#example-usage

```terraform
#
# Send a PagerDuty notification
#

data "sentry_organization_integration" "pagerduty" {
  organization = sentry_project.test.organization

  provider_key = "pagerduty"
  name         = "PagerDuty"
}

resource "sentry_issue_alert" "pagerduty_alert" {
  actions = <<EOT
[
  {
    "id": "sentry.integrations.pagerduty.notify_action.PagerDutyNotifyServiceAction",
    "account": ${parseint(data.sentry_organization_integration.pagerduty.id, 10)},
    "service": 9823924
  }
]
EOT
  // ...
}
```
