### ISSUE TITLE
No replacement for the deprecated `dsn_secret` in `sentry_key` resource

### ISSUE THREAD

**Issue by khaledez** [jianyuan/terraform-provider-sentry#321]
Hello,
As per deprecation notice. I updated our code to use `sentry_key.secret` instead of `sentry_key.dsn_secret` but that didn't work!

I had to rollback to the deprecated value. After checking the code: https://github.com/jianyuan/terraform-provider-sentry/blob/main/sentry/data_source_sentry_key.go#L168C4-L171 
the new `sentry_key.secret` uses a different attribute!

Is this a bug in the current version? or do you have a replacement for `dsn_secret`?

**Comment by jianyuan** [comment]
I'm going to close this for now as I believe Sentry repurposed the fields for something else.
