### ISSUE TITLE
Support setting the owner in the sentry_issue_alert resource

### ISSUE THREAD

**Issue by tokyowizard** [jianyuan/terraform-provider-sentry#323]
The "owner" in an issue alert changes to "Unassigned" after running terraform apply. Could the "owner" be specified as well?

When I import an issue alert using the `sentry_issue_alert` resource, the conditions and actions aren't included in the import.
I add the conditions and actions to match what's already in the alert, then run `apply` in Terraform.

I'm just trying to sync the terraform state with the issue alerts in Sentry. There should be no changes to the issue alert, but the owner changes to "Unassigned".

Before applying, the owner is set:
![Screenshot 2023-09-07 at 11 57 14](https://github.com/jianyuan/terraform-provider-sentry/assets/3119405/149bcba7-9712-41bd-9486-5b3230c57e8e)

After import and apply, the owner changes to `Unassigned`:
![Screenshot 2023-09-07 at 11 57 28](https://github.com/jianyuan/terraform-provider-sentry/assets/3119405/18670681-8598-47ce-8f60-843818be6b28)

**Comment by jianyuan** [comment]
The option to set the `owner` is now available in [v0.12.0](https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/issue_alert#owner)!
