### ISSUE TITLE
resource import instructions missing for the `sentry_dashboard` resource

### ISSUE THREAD

**Issue by nialdaly** [jianyuan/terraform-provider-sentry#327]
For the `sentry_dashboard` resource, there doesn't appear to be any instructions for how to import existing dashboards into Terraform state management.

<img width="1097" alt="Screenshot 2023-09-14 at 13 51 39" src="https://github.com/jianyuan/terraform-provider-sentry/assets/34862917/10ed69d2-21d8-4fae-a8ee-fbef2b39f709">

I've added a [PR](https://github.com/jianyuan/terraform-provider-sentry/pull/326) to include the neccessary markdown! Thanks!

**Comment by krysal** [comment]
This is solved @jianyuan ✅
