### ISSUE TITLE
Is 0.12 coming?

### ISSUE THREAD

**Issue by gcar-bendingspoons** [jianyuan/terraform-provider-sentry#350]
I see there are many new features and fixes in this provider, which is great and I'd love to use them!

I currently built it myself and I'm installing it from the filesystem, but it's a bit hacky and doesn't integrate well e.g. with our CI.

Do you have plans on a new release any time soon?

Thanks a lot for the great work! 🙏

**Comment by jianyuan** [comment]
Yes! It's coming within this week.

**Comment by jianyuan** [comment]
Released!

**Comment by gcar-bendingspoons** [comment]
Amazing! Thanks a lot 🙏
