### ISSUE TITLE
Inconsistent result bug with sentry_team_member resource

### ISSUE THREAD

**Issue by pgjones** [jianyuan/terraform-provider-sentry#364]
As output by terraform apply,
```
Provider produced inconsistent result after apply
│ 
│ When applying changes to sentry_team_member.default["REDACTED"], provider "provider[\"registry.terraform.io/jianyuan/sentry\"]" produced an unexpected new value: .role: was
│ cty.StringVal("admin"), but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

I'm trying to add members to a team, happy to provide more information as requested.

**Comment by LucasMrqes** [comment]
I am having the same issue, on a different ressource (`sentry_notification_action`): 

```
When applying changes to sentry_notification_action.sentry_notification["<my_project_slug>"], provider "provider[\"registry.terraform.io/jianyuan/sentry\"]" produced an unexpected new value: .projects[0]: was cty.StringVal("<my_project_slug>"), but now cty.StringVal("").
```

**Comment by jianyuan** [comment]
@pgjones Thanks for the report. Is the user already an organization-level admin or higher? I noticed that Sentry internally sets the role to `null` if the user already has better permissions and that causes an issue with Terraform.

**Comment by pgjones** [comment]
One was, but I think this errors for all the users I've tried.

**Comment by jianyuan** [comment]
@pgjones I think we need to implement this effective role method in the TF provider. I will look into this later this week.

https://github.com/getsentry/sentry/blob/c085ab3bbefba9b2e857527cf734e490ccef8f70/src/sentry/api/endpoints/organization_member/team_details.py#L361-L371
https://github.com/getsentry/sentry/blob/c085ab3bbefba9b2e857527cf734e490ccef8f70/static/app/components/teamRoleSelect.tsx#L42C28-L42C47

**Comment by jianyuan** [comment]
I have devised a fix. I will be releasing v0.12.2 shortly.

**Comment by buzztaiki** [comment]
@jianyuan Thank you for fixing it! When do you think v0.12.2 will be released?

**Comment by jianyuan** [comment]
@buzztaiki It's out now!

**Comment by buzztaiki** [comment]
@jianyuan Thank you!
