### ISSUE TITLE
`sentry_issue_alert.conditions` is nullable

### ISSUE THREAD

**Issue by kenkoooo** [jianyuan/terraform-provider-sentry#366]
While using `sentry_issue_alert`, I noticed that the `conditions` parameter is expected to be non-null by the provider, despite the API documentation indicating otherwise. Interestingly, if an empty list is passed, the provider internally converts it to `null` before submitting it through the API. This results in successful resource updates, but it also triggers an error due to the mismatch between the response value (`null`) and the originally passed value (`[]`). It would be appreciated if this behavior could be reviewed for alignment with the documentation.

**Comment by phyzical** [comment]
i also ran into this my current workaround is to ignore the changes and manage it via the ui for the time being

```
lifecycle {
    ignore_changes = [
      conditions,
      filters
    ]
  }
 ```

**Comment by pipt** [comment]
We're seeing this issue too, having a fix merged soon would be great!
