### ISSUE TITLE
produced an unexpected new value: .role: was null, but now cty.StringVal("admin").

### ISSUE THREAD

**Issue by axelfulop** [jianyuan/terraform-provider-sentry#370]
Hello, we noticed that the provider was updated, so when we tried to also update the resources we are having the following error:

When applying changes to sentry_team_member.admins["asaf@livekindred.com"], provider "provider[\"registry.terraform.io/jianyuan/sentry\"]" produced an unexpected new value: .role: was null, but now cty.StringVal("admin").

![image](https://github.com/jianyuan/terraform-provider-sentry/assets/11843834/344bb746-e235-4191-8810-c7103d582306)

```

Terraform cfg:

terraform {
  backend "remote" {
    organization = "kindred"

    workspaces {
      name = "aws-root"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.35.0"
    }
    datadog = {
      source = "DataDog/datadog"
    }

    sentry = {
      source = "jianyuan/sentry"
    }
  }
  required_version = ">= 1.2.0"
}

provider "aws" {
  region = var.region
  default_tags {
    tags = local.tags
  }
}


provider "datadog" {
  api_key = var.dd_api_key
  app_key = var.dd_app_key
}

provider "sentry" {
  token    = var.sentry_auth_token
}


Sentry.tf
resource "sentry_organization_member" "admins" {
  for_each = { for user in local.admin_group : user.email => user }

  organization = "kindred-concepts-com"
  email        = each.value.email
  role         = lookup(each.value.sentry, "role", "member")
}


resource "sentry_organization_member" "devs" {
  for_each = { for user in local.developer_group : user.email => user }

  organization = "kindred-concepts-com"
  email        = each.value.email
  role         = lookup(each.value.sentry, "role", "member")
}
resource "sentry_team_member" "admins" {
  for_each = { for key, member in sentry_organization_member.admins : key => member }

  organization = "kindred-concepts-com"
  team         = "eng"
  member_id    = each.value.internal_id

  depends_on = [sentry_organization_member.admins]
}

resource "sentry_team_member" "devs" {
  for_each = { for key, member in sentry_organization_member.devs : key => member }

  organization = "kindred-concepts-com"
  team         = "eng"
  member_id    = each.value.internal_id

  depends_on = [sentry_organization_member.devs]
}
```

Then i tried to figure out what was going on so commented the sentry cfg and files and having this error:

Error: Client Error

unable to find team member

If i comment the sentry part, still having same issue
{“@level”:“error”,“@message”:“Error: Client Error”,“@module”:“terraform.ui”,“@timestamp”:“2024-01-03T11:54:11.330155Z”,“diagnostic”:{“severity”:“error”,“summary”:“Client Error”,“detail”:“unable to find team member”},“type”:“diagnostic”} Operation failed: failed running terraform plan (exit 1) terraform cloud plan

Any help?

**Comment by jianyuan** [comment]
It seems to be related to https://github.com/jianyuan/terraform-provider-sentry/issues/364

**Comment by jianyuan** [comment]
I have devised a fix. I will be releasing v0.12.2 shortly.

**Comment by deiga** [comment]
@jianyuan You didn't release the tag and it can't be found by terraform, please release the fix 🙏

**Comment by jianyuan** [comment]
@deiga Whoops, forgot to click Publish 🤦 . It's out now! Thanks for letting me know!
