### ISSUE TITLE
Provider to list all DSNs for a project

### ISSUE THREAD

**Issue by realkosty** [jianyuan/terraform-provider-sentry#375]
Opening this on behalf of a Sentry customer.

We have [a data source for fetching DSN](https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/data-sources/key). However it's limited to either first DSN key or a key with a known name.

Our customer would like to be able to list ALL DSN keys for a given project. It needs to be implemented in such way that it can be used from an inner loop, or whatever’s Terraform’s equivalent, when using the separately requested list-all-projects data source (not currently implemented).

Background:
Customer's use case is to apply a rate limit to every DSN in a project for every single project. For each project its respective rate limit will be looked up from a hardcoded list and if not on the list (new project) a pre-determined default rate limit rate will be applied. The goal of this is to enforce default rate limit on any newly created projects.

**Comment by Dhrumil-Sentry** [comment]
@jianyuan Does the existing data source for keys support this already?

**Comment by jianyuan** [comment]
@Dhrumil-Sentry Currently, the data source can only fetch the first key or a key that matches a name.

**Comment by jianyuan** [comment]
This will be available in the upcoming release as the `sentry_all_keys` data source.
