### ISSUE TITLE
Support Alerts

### ISSUE THREAD

**Issue by G-Rath** [jianyuan/terraform-provider-sentry#39]
While not documented, it exists :)

https://forum.sentry.io/t/feature-request-manage-projects-alerts-via-api/5667

(In a few months once I've gotten a few things off my plate, and start actively working on a terraform project I'll be happy to contribute to this provider)

**Comment by coopergillan** [comment]
Awesome work over in #45! 

@jianyuan - wondering if you'd be able to cut a release soon that has the alerts code?

Thanks!

**Comment by coopergillan** [comment]
@jianyuan - this issue can be closed it looks like 👍
