### ISSUE TITLE
API errors lead to state file being wiped

### ISSUE THREAD

**Issue by taiidani** [jianyuan/terraform-provider-sentry#40]
On the `master` version of this provider (Terraform 0.12), I encountered behavior where some unknown event let to all Sentry resources disappearing from my tfstate file.

The going theory is that a problem with the Refresh/GET operation occurred on the Sentry side which instead of causing a failure caused this provider to return empty objects, leading to a success status and an empty payload.

I've seen similar behavior before when a Sentry API key is provided that doesn't have sufficient access to GET the resources from the API. Instead of erring out it succeeds and declares the resource to be non-existent, when in fact it does exist and the Provider doesn't have access to see it.

**Comment by remilapeyre** [comment]
I have this issue, importing them back works as a workaround but it would be better in the provider could only remove them if it got an actual response from the API.

**Comment by jianyuan** [comment]
Fixed in #70.
