### ISSUE TITLE
Changed sentry_key DSNs

### ISSUE THREAD

**Issue by foggypete** [jianyuan/terraform-provider-sentry#405]
After we updated from version 0.11.2 to 0.12.2 we noticed a change to the DSNs of our sentry keys.
The domain in the DSNs had changed from `.ingest.sentry.io` to `.ingest.us.sentry.io`. We are managing our own sentry keys and have set `default_key = false` on our projects as a result.

```
resource "sentry_project" "_" {
  for_each = local.sentry_projects

  organization  = sentry_organization._.slug
  teams         = [sentry_team._.slug]
  name          = each.value.sentry.name
  slug          = each.value.sentry.name
  platform      = "python"
  resolve_age   = 7 * 24
  default_key   = false
  default_rules = false
}

resource "sentry_key" "_" {
  for_each = sentry_project._

  organization = sentry_organization._.slug
  project      = each.value.slug
  name         = each.value.slug
}
```

We subsequently set a `SENTRY_DSN` env var on our ECS tasks using the created sentry keys,
```
data "sentry_key" "_" {
  organization = "xxx"
  project      = "xxx"
  name         = "xxx"
}
```
`SENTRY_DSN = data.sentry_key._.dsn_public`

The relevant plan output is:
```
~ {
    name  = "SENTRY_DSN"
    ~ value = "https://xxx@oxxx.ingest.sentry.io/xxxxx" -> "https://xxxx@oxxxx.ingest.us.sentry.io/xxxxx"
},
```

Is this intended behaviour  or should the DSNs on our sentry keys not have changed? The keys were created prior to the upgrade to version 012.2 of the provider.

**Comment by jianyuan** [comment]
@foggypete I believe this is due to Sentry transitioning to a multi-region environment. Here is a related comment:

https://github.com/getsentry/sentry/issues/65924#issuecomment-1969419177

The TF provider simply reads the Sentry DSN from the API and does not do any post-processing.
