### ISSUE TITLE
[Data residency] Support for EU data residency in organisation resource

### ISSUE THREAD

**Issue by smrutimandal** [jianyuan/terraform-provider-sentry#414]
Hi,

At the moment there is no way specify the data residency of organisation when creating it through terraform.

Do you have any plans to add data location to the `sentry_organization` resource?

**Comment by jianyuan** [comment]
Hi @smrutimandal, the region is configured at a provider level. You can currently switch region by setting the base URL to one of the following:

1. https://de.sentry.io/api/ for the EU
2. https://us.sentry.io/api/ for the US

```tf
provider "sentry" {
  base_url = "https://de.sentry.io/api/"
}
```

On the provider side, I will update the documentation and add a `region` flag with preconfigured URLs e.g.

```tf
provider "sentry" {
  region = "EU"
}
```
