### ISSUE TITLE
Sentry not using `slug` input

### ISSUE THREAD

**Issue by angelov-g** [jianyuan/terraform-provider-sentry#419]
I've created a module which I'm giving some values through variables (e.g. `project_name`, `project_slug`, etc.)
However after the resource is created and I try to change one of the values for the `sentry_project` resource which my module is based around I don't see any changes in the planning phase. Therefore after apply, the changes are only in my code and not visible in the Sentry UI.

**Comment by angelov-g** [comment]
I should mention I'm trying to change the `slug` of the project. Is this something impossible?

**Comment by jianyuan** [comment]
@angelov-g I believe Sentry now displays the name as the slug throughout the site. If you set both the name and slug to the same value, it should work.

For reference: In this updated project form, the frontend code sets the name and slug to the same value.

[View source code](https://github.com/getsentry/sentry/blob/c95342cf7c3a92f060bfc63216c6a2df253637ab/static/app/data/forms/projectGeneralSettings.tsx#L59-L64)

![image](https://github.com/jianyuan/terraform-provider-sentry/assets/103584/decc1834-af6f-435a-be85-676ca7cc2967)

**Comment by angelov-g** [comment]
I haven't tried updating the name of the resource. I'll try leaving the slug parameter unset and only use the name. I'll let you know what happens.

**Comment by angelov-g** [comment]
To be honest I just played around with this, the slug is not show anywhere. I tried setting the `name` as `test project name` and `slug` as `test-project-slug` and I don't see the second one anywhere
