### ISSUE TITLE
Ignore Whitespace changes with jsonencode

### ISSUE THREAD

**Issue by victorchan88** [jianyuan/terraform-provider-sentry#456]
HI, I wanted to know if you guys have any idea how to fix whitespace changes from showing up on terraform plan. They seem to only occur when I do jsonencode(). It seems like you have written [code](https://github.com/jianyuan/terraform-provider-sentry/blob/0b6f73750913b30fb1ea9e0610635c538db26dd6/sentry/helpers.go#L43) to handle this but it doesn't seem to be able to normalize jsonencode() stuff.

**Comment by jianyuan** [comment]
Please continue in https://github.com/jianyuan/terraform-provider-sentry/issues/529.
