### ISSUE TITLE
Adding "client security" settings for projects

### ISSUE THREAD

**Issue by jleclanche** [jianyuan/terraform-provider-sentry#46]
Is it possible to add all these from project settings?

![image](https://user-images.githubusercontent.com/235410/67970351-23625f00-fc0b-11e9-9f3c-804eb59c2303.png)

`allowed_domains` (as a list of strings) would especially be useful, and `security_token` as well.

**Comment by billyors** [comment]
+1 for the additional project settings. Checked to see if there had been any update on this since the ghi opened and it doesn't look like the provider supports `security_token` yet.
