### ISSUE TITLE
[Feature Request] sentry_key resource support for setting dynamicSDKLoader options

### ISSUE THREAD

**Issue by dgeorges** [jianyuan/terraform-provider-sentry#467]
The sentry api to create a new sentry key (see https://docs.sentry.io/api/projects/create-a-new-client-key/) by default sets the dyanmicSDKLoader options hasReplay, hasPerformance and hasDebug to true.

To change these defaults you can use the update key api (https://docs.sentry.io/api/projects/update-a-client-key/)

Request: Provide support to set these values, within the sentry_key resource or outside of it. 

Use case:
Not everyone wants all these options turned on by default. It could be for performance, privacy or quota reasons.
Allowing it to be explicit will allow users to decide.

**Comment by gauthamcs** [comment]
@dgeorges : 
> Request: Provide support to set these values, within the sentry_key resource or outside of it.

To clarify, is the ask to be able to set these values via the Terraform provider or something different?

**Comment by dgeorges** [comment]
> @dgeorges :
> 
> > Request: Provide support to set these values, within the sentry_key resource or outside of it.
> 
> To clarify, is the ask to be able to set these values via the Terraform provider or something different?

Yes, The ask is be able to provide those values via this Terraform provider. The "outside of it" part was to mean that the properties could be set via the sentry_key resource or some other terraform resource in this provider. I am sure the API will influence the implementation.
