### ISSUE TITLE
Projection creation if the project already exists.

### ISSUE THREAD

**Issue by fa93hws** [jianyuan/terraform-provider-sentry#47]
Hi

If an existing project (say, "web-app") is being created via the web API, it seems that it will create one with some random string suffix ("web-app9p" for example)

Do you think it would be more appropriate to `retrieve` first and skip if it exists?

**Comment by jianyuan** [comment]
Hey @fa93hws,

By web API, did you mean something other than this Terraform provider (for example, via the web UI)?

If so, do you think doing a [`terraform import sentry_project.default org-slug/project-slug`](https://www.terraform.io/docs/import/index.html) would solve this issue?

**Comment by fa93hws** [comment]
Ah! Many thanks!
