### ISSUE TITLE
[Bug]  Can't find Sentry Organization Repository:

### ISSUE THREAD

**Issue by phyzical** [jianyuan/terraform-provider-sentry#470]
not sure when this started but currently api calls return `Error: Can't find Sentry Organization Repository: ORG/REPO`

if you remove existing or add new ones, they are added in the sentry ui but the provider seems to think they are not?

**Comment by leandroandrade-hotmart** [comment]
3 days ago worked fine to me, but today i've got the same error.

**Comment by benlangfeld** [comment]
This is completely blocking my use of this provider. Can this please be given maximum priority @jianyuan ?

**Comment by phyzical** [comment]
i did try investigating, all i can say is the api call it hits (when i tested via curl) still returns the items as expected. 

```
[{"id":"12345","name":"ORG/REPO","url":"https://github.com/ORG/REPO","provider":{"id":"integrations:github","name":"GitHub"},"status":"active","dateCreated":"2023-08-28T18:26:01.234675Z","integrationId":"61069","externalSlug":"ORG/REPO","externalId":"12345"}]
```

https://github.com/jianyuan/terraform-provider-sentry/blob/afcd12953a5ceeab958bf3487056d1ebc2bd070d/sentry/resource_sentry_organization_repository_github.go#L111

This function was always returning empty keys and the error listed above

thats where i got stuck as it all looks pretty generic inside  https://github.com/jianyuan/go-sentry/blob/954549eb82287b6e8f1bf795f4e23d622e1ca19c/sentry/organization_repositories.go#L43

if i was to guess the format of the json has changed?

the only thing thing i've noticed is the spec has changed 

https://github.com/getsentry/sentry/blob/22.7.0/src/sentry/api/serializers/models/repository.py
vs 
https://github.com/getsentry/sentry/blob/master/src/sentry/api/serializers/models/repository.py

im trying to workout how to use local go modules to test if its the schema but i dont go much

**Comment by benlangfeld** [comment]
> i did try investigating, all i can say is the api call it hits (when i tested via curl) still returns the items as expected.
> 
> ```
> [{"id":"12345","name":"ORG/REPO","url":"https://github.com/ORG/REPO","provider":{"id":"integrations:github","name":"GitHub"},"status":"active","dateCreated":"2023-08-28T18:26:01.234675Z","integrationId":"61069","externalSlug":"ORG/REPO","externalId":"12345"}]
> ```
> 
> https://github.com/jianyuan/terraform-provider-sentry/blob/afcd12953a5ceeab958bf3487056d1ebc2bd070d/sentry/resource_sentry_organization_repository_github.go#L111
> 
> This function was always returning empty keys and the error listed above
> 
> thats where i got stuck as it all looks pretty generic inside https://github.com/jianyuan/go-sentry/blob/954549eb82287b6e8f1bf795f4e23d622e1ca19c/sentry/organization_repositories.go#L43
> 
> if i was to guess the format of the json has changed?

I also observed the same as you.

**Comment by benlangfeld** [comment]
So the problem is between https://github.com/jianyuan/go-sentry/blob/main/sentry/organization_repositories.go#L36-L38 and https://github.com/getsentry/sentry/pull/75409.

```
❯ curl https://sentry.io/api/0/organizations/SLUG/repos/\?query\=ORG/REPO\&status\= -H 'Authorization: Bearer TOKEN'
[]%                                                                                                                                                                                               
❯ curl https://sentry.io/api/0/organizations/SLUG/repos/\?query\=ORG/REPO -H 'Authorization: Bearer TOKEN'
[{"id":"12345","name":"ORG/REPO","url":"https://github.com/ORG/REPO","provider":{"id":"integrations:github","name":"GitHub"},"status":"active","dateCreated":"2023-08-16T04:20:10.326903Z","integrationId":"56708","externalSlug":"ORG/REPO","externalId":"54321"}]
```

**Comment by jianyuan** [comment]
Thanks for reporting the issue. I will investigate.

**Comment by benlangfeld** [comment]
> Removing `status=` from the URL when it is blank should fix the problem.

I don't think that's desirable; that's how this provider ensures it can find inactive repos.

I think the correct course of action is https://github.com/getsentry/sentry/pull/75455 and closing this issue once that is deployed to sentry.io.

**Comment by jianyuan** [comment]
@benlangfeld Ah, I see. Makes sense. Thanks!

**Comment by phyzical** [comment]
Can confirm upstream has fixed the issue 🎉
