### ISSUE TITLE
Error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by fl-max** [jianyuan/terraform-provider-sentry#49]
```
Error: invalid character '<' looking for beginning of value

  on sentry.tf line 13, in resource "sentry_team" "test":
  13: resource "sentry_team" "test" {
```

This error occurs when missing the `/api/` suffix to the Base URL. I know the Docs give an example `base_url` but I interpreted "base url" as the base url to my Sentry installation at first.

Maybe add this to the Docs or have the Provider first check the URL if it is valid and return a more meaningful error?

**Comment by jianyuan** [comment]
[This will soon be handled in the Client Library](https://github.com/jianyuan/go-sentry/issues/39).
