### ISSUE TITLE
Creating issue alerts with Jira action step requires me to fill in all dynamic_form_fields which creates a lot of extra lines of code

### ISSUE THREAD

**Issue by Angelodaniel** [jianyuan/terraform-provider-sentry#525]
I've been trying to use the Sentry Terraform provider to setup a Jira alert rule, but it's not gone as expected. I initially had this actions list definition:
```
resource "sentry_issue_alert" "jira_alert" {
...
actions    = <<EOT
[
  {
    "integration": "${local.jira_integration_id}",
    "project": "${local.*_jira_project_id}",
    "issueType": "${local.support_request_issue_type}",
    "id": "sentry.integrations.jira.notify_action.JiraCreateTicketAction"
  }
]
EOT
}
```
I double checked all the locally defined values were correct, but when trying to apply this got the following error:
```
Error: Client Error
│ 
│   with sentry_issue_alert.jira_alert,
│   on * line 84, in resource "sentry_issue_alert" "jira_alert":
│   84: resource "sentry_issue_alert" "jira_alert" {
│ 
│ Error creating issue alert: POST
│ https://sentry.io/api/0/projects/*/*/rules/: 400
│ map[actions:[Must configure issue link settings.]]
```
This was confusing as the field defined originally should have been all thats required to create a Jira ticket on our board. On further investion we found it works if we include 5000+ lines of extra dynamic_form_fields configuration to define everything the Issue Link Settings form might have and appears to be included in the UI version of the Issue Link Settings dialogue, despite none of those extra fields actually being set or required.
This make the file very unwildy and seems quite brittle, as it includes e.g. all the Jira projects on our Jira instance. Are all these extra fields really necessary? It doesn't seem like this is the intended way to set up such an alert rule. Can you help at all to explain why the extra config was required and if theres something we can do to avoid it?

I have to provide at least the choices for the dialogue. But I don't have to actually fill in the values in a way where the created jira ticket would use them. This includes the reporter field which we have added like this
```
{
  "choices": [],
  "label": "Reporter",
  "name": "reporter",
  "required": false,
  "type": "select",
  "url": "/extensions/jira/search/*/*/"
}
```

**Comment by jianyuan** [comment]
Please continue in https://github.com/jianyuan/terraform-provider-sentry/issues/529.
