### ISSUE TITLE
Platform not added on project creation

### ISSUE THREAD

**Issue by phlegx** [jianyuan/terraform-provider-sentry#54]
For some reason when adding a new project, the platform is not set in Sentry. I have to run `terraform apply` a second time, only then the platform is added. 

Any ideas?

**Comment by adrian-rivera** [comment]
The Sentry API does not support adding the platform when creating a project, to do this you would need to create a project and then run an update, that's why the second `terraform apply` works.

**Comment by jianyuan** [comment]
Thank you for your PR, @adrian-rivera.

Fixed in #61.
