### ISSUE TITLE
Authentication needed

### ISSUE THREAD

**Issue by ChargemapFranck** [jianyuan/terraform-provider-sentry#552]
Hello,

Without any changes on our side (same terraform code, same key, same version of the provider : 0.14.1) the plan is not working anymore. 
Tuesday it was working great but now it fails everytime.
We got this provider error : 

```
│ 
│ Error: Client error
│ 
│   with data.sentry_organization.main,
│   on sentry.tf line 1, in data "sentry_organization" "main":
│    1: data "sentry_organization" "main" {
│ 
│ Unable to read, got status 200: 
│ 
│ 
│ 
│ 
│ 
│ 
│ <!DOCTYPE html>
│ <html lang="en">
│ <head>
│   <meta http-equiv="content-type" content="text/html; charset=utf-8">
│   <!-- The "none" directive is equivalent to using both the noindex and nofollow tags simultaneously -->
│   <meta name="robots" content="none, noarchive">
│   <meta name="viewport" content="width=device-width, initial-scale=1">
(i'm trimming the full html page)
[01JG151K81AYZWEKHABF2YRCXB] Unexpected exit code when planning changes: 1
```

the rest of the error is a html page with this error : 
`<b>{{our organization name}}</b> requires signing in with Google.
`

This is our terraform code for this part :
```
data "sentry_organization" "main" {
  slug = local.sentry_organization_name
}

data "sentry_team" "devs" {
  organization = data.sentry_organization.main.slug
  slug         = "devs"
}

resource "sentry_project" "sentry-projects" {
  for_each = local.sentry-projects

  organization = data.sentry_team.devs.organization
  teams = [data.sentry_team.devs.slug]
  name         = each.key
  platform     = each.value
  default_key  = false
  digests_max_delay = 1800
  digests_min_delay = 300
}

resource "sentry_key" "sentry_keys" {
  for_each = sentry_project.sentry-projects

  organization      = each.value.organization
  project           = each.value.slug
  name              = each.value.name
  rate_limit_count  = 100
  rate_limit_window = 900 // 15 minutes
}
```

I bet the sentry api changed on their side but the sentry support told me to write an issue here for the provider support.
Thanks for the help.

**Comment by ChargemapFranck** [comment]
Update : turns out we were using the last version with this constraint ~> 0.14.1 we got the 0.14.3.
I tried with the fixed version 0.14.1 : it works, 0.14.2 : got the error, 0.14.3 : got the error.

Is there any changes between 0.14.1 and 0.14.2 that could result to this error ?
Let me know if you need more information. I would be glad to help.

**Comment by ChargemapFranck** [comment]
Hello, yes this curl call is working I get my organization details.
The thing I don't get is why do we get a HTML response with the provider. We have indeed a sso connection with google with sentry but it should not be the case for api calls.
Is there a debug version of the provider that can log api calls ?

**Comment by ChargemapFranck** [comment]
Hello again,
I finally found out what was going on. Well.. it was an old misconfiguration on our side with the "base_url" which was pointing to https://chargemap.sentry.io instead of the default one. 
It turns out in 0.14.1 it was ignoring it but until the 0.14.2 it was using it and pointing on the wrong url. 
Sorry for the inconvenience and thanks for your response.

**Comment by ChargemapFranck** [comment]
Hello again,
I finally found out what was going on. Well.. it was an old misconfiguration on our side with the "base_url" which was pointing to https://{our_organization}.sentry.io instead of the default one.
It turns out in 0.14.1 it was ignoring it but until the 0.14.2 it was using it and pointing on the wrong url.
Sorry for the inconvenience and thanks for your response.

**Comment by jianyuan** [comment]
@ChargemapFranck Thanks, that was helpful. Perhaps the provider could ping https://sentry.io/api/0/internal/health/ to make sure the URL is set up correctly.

**Comment by jianyuan** [comment]
https://github.com/jianyuan/terraform-provider-sentry/pull/553
