### ISSUE TITLE
TaggedEventCondition not valid

### ISSUE THREAD

**Issue by neckhair** [jianyuan/terraform-provider-sentry#62]
The following `sentry_rule` condition returns a validation error.

```terraform
conditions = [
    {
      id = "sentry.rules.conditions.tagged_event.TaggedEventCondition"
      key = "environment"
      match = "eq"
      value = "staging"
    }
  ]
```

Error: sentry: map[conditions:[Ensure at least one action is enabled and all required fields are filled in.]]

It looks like the underlying sentry client library doesn't support the `match` attribute, is that right?

**Comment by budgester** [comment]
I think what you need in the rule is an action, as specified in the error message. "Ensure at least one action is enabled"

`resource "sentry_rule" "test" {
    name = "Send a notification for new issues"
    organization = var.organization
    project = sentry_project.test.name
    action_match = "any"
    frequency    = 10
    environment = ""
    conditions = [
      {
        id       = "sentry.rules.conditions.every_event.EveryEventCondition"
      }
    ]

    actions = [
      {
        id        = "sentry.integrations.slack.notify_action.SlackNotifyServiceAction"
        channel   = var.test_channel
        name = "Send a notification via slack"
        label = "Send a slack notification"
        workspace = var.slack
        tags = "test"
      }
    ]
}
`

**Comment by zopz** [comment]
FYI looks like this was a validation issue within the module that has since been fixed, see https://github.com/jianyuan/terraform-provider-sentry/issues/65

@neckhair original formatting should work fine if you upgrade, ex.
```
resource "sentry_rule" "k8s_send_webhook" {
  organization = var.organization_name
  project      = "kubernetes"
  action_match = "any"
  frequency    = 5
  name         = "Notify when system OOM"

  actions = [
    {
      id = "sentry.rules.actions.notify_event.NotifyEventAction"
    }
  ]

  conditions = [
    {
      id = "sentry.rules.conditions.tagged_event.TaggedEventCondition"
      key = "reason"
      match = "eq"
      value = "SystemOOM"
    }
  ]
}
```

**Comment by jianyuan** [comment]
It looks this has been fixed. Let me know if the issue persists.
