### ISSUE TITLE
No data provider to get existing integrations

### ISSUE THREAD

**Issue by gone** [jianyuan/terraform-provider-sentry#63]
The slack workspace command needs the ID of the integration, but I can't fetch without using the resource and specifying details such as webhook destination.

**Comment by jianyuan** [comment]
There is now a "sentry_organization_integration" data source in v0.10.0.

https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/data-sources/organization_integration


### Usage
```tf
data "sentry_organization_integration" "slack" {
  organization = "my-organization"
  provider_key = "slack"
  name         = "Slack Workspace Name"
}
```
