### ISSUE TITLE
Project Team not updating

### ISSUE THREAD

**Issue by barroca** [jianyuan/terraform-provider-sentry#67]
Hello, when I run a plan to change the team for a project, i see the changes like this: 

`sentry_project.serviceA
    team:   "teamA" => "teamB"`

But when applying they don't affect Sentry (I cannot see the change on their side).

I have a guess that we are missing the team information on the code here:
https://github.com/jianyuan/terraform-provider-sentry/blob/b9d9128003fe67c9a0b41dcf9209e4bdd0b38353/sentry/resource_sentry_project.go#L142

**Comment by brandonweng-db** [comment]
Also seeing the same thing for our use case. 

Would this just be adding this in resourceSentryProjectUpdate? 
```
	platform := d.Get("team").(string)
	if platform != "" {
		params.Team = team
	}
```

**Comment by taiidani** [comment]
Running into the same problem on my side. The `apply` will no-op and the drift will persist into the next `plan`.

Slight iteration on @brandonweng-db 

```go
team := d.Get("team").(string)
if team != "" {
    params.Team = team
}
```

**Comment by bilalahmad99** [comment]
facing same issue

**Comment by semangard** [comment]
same issue

**Comment by jianyuan** [comment]
It seems that the team name has been deprecated. Sentry just needs a unique slug, which is reflected in the web UI. I will look into this.

**Comment by everops-billm** [comment]
I'm having this issue too. It would also be helpful to be able to add additional teams to a project using the project provider, like you can from the web UI, or conversely add projects to the teams resources, also like you can do in the Web UI.

**Comment by jebeaudet** [comment]
Any update on this? Thanks

**Comment by mogagnon** [comment]
The problem comes from the way the API handles the addition of a team. Updating a team with the same call the provider does is deprecated. 

> The slug of new team for the project. Note, will be deprecated soon when multiple teams can have access to a project.


As far as I understand, the new way of managing a team for a project is with those two calls.
```
POST /projects/org_slug/project_slug/teams/teams_slug
DELETE /projects/org_slug/project_slug/teams/teams_slug
```

I have a fix on the way but as @everops-billm mentioned it would be nice to support multiple teams

**Comment by mogagnon** [comment]
Follows up for those that are interested. There are two pr to fix this bug, one is in [sentry-go](https://github.com/jianyuan/go-sentry/pull/22) and the other one which is still a draft is [here](https://github.com/jianyuan/terraform-provider-sentry/pull/116).

**Comment by jianyuan** [comment]
Thanks for your draft PR, @mogagnon! I've adapted your changes to https://github.com/jianyuan/terraform-provider-sentry/pull/172.
