### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by s-yagodkin** [jianyuan/terraform-provider-sentry#68]
Hello, latest release tag and master are quite different now. There is issue - https://github.com/jianyuan/terraform-provider-sentry/issues/56 which resolved, but still not in release (even patch one). Is there any possibility to expect new release any time soon? Thank you!

**Comment by jianyuan** [comment]
[v0.5.4](https://github.com/jianyuan/terraform-provider-sentry/releases/tag/v0.5.4) has been released!
