### ISSUE TITLE
Option to delete project default sentry key

### ISSUE THREAD

**Issue by joshgummersall** [jianyuan/terraform-provider-sentry#71]
When you create a project, a key is created automatically behind the scenes by Sentry. In order to reference a sentry key in a declarative way, one must create a duplicate key for that project separately.
```
resource "sentry_project" "default" {
  organization = sentry_org.default.slug
  team = sentry_team.default.slug
  name = "default project"
}

resource "sentry_key" "default" {
  organization = sentry_org.default.slug
  project = sentry_project.default.slug
  name = "default"
}
```

This will result in two keys defined on the project, though. You could use a `data` source, but that will fail until the project and key are created (i.e. we need a way to break the cycle, or do something like the above and pollute the keys for a project).

I would like to introduce a new bool project resource parameter, `remove_default_key`, that removes the default project key when creating a project. It's similar in semantic meaning to the [remove_default_node_pool](https://www.terraform.io/docs/providers/google/r/container_cluster.html#remove_default_node_pool) parameter on the Terraform Google Cluster resource. The default value would be false.

Then, this would yield only a single key:

```
resource "sentry_project" "default" {
  organization = sentry_org.default.slug
  team = sentry_team.default.slug
  name = "default project"
  remove_default_key = true
}

resource "sentry_key" "default" {
  organization = sentry_org.default.slug
  project = sentry_project.default.slug
  name = "default"
}
```

Is that reasonable? I wanted to open an issue to discuss before diving in to the code.

**Comment by insertjokehere** [comment]
Not the project maintainer, but I'd find such functionality very useful!
