### ISSUE TITLE
support for adding multiple teams in a project

### ISSUE THREAD

**Issue by bilalahmad99** [jianyuan/terraform-provider-sentry#86]
is there a way currently to add more than 1 team to a project?

**Comment by jianyuan** [comment]
I prefer to have a new resource for this. i.e. `sentry_project_team`.

Example usage:

```terraform
resource "sentry_project" "default" {
  organization = "my-organization"

  team = "my-team"
  name = "web-app"
}

resource "sentry_project_team" "my_team" {
  organization = sentry_project.default.organization

  project = sentry_project.default.slug
  team    = "my-team"
}

resource "sentry_project_team" "your_team" {
  organization = sentry_project.default.organization

  project = sentry_project.default.slug
  team    = "your-team"
}
```

The team property in the "sentry_project" may be confusing. Ideally, we should omit this but the API expects a team on creation. So, I propose renaming it to "initial_team".

```terraform
resource "sentry_project" "default" {
  // the rest
  initial_team = "my-team"
}
```

**Comment by mhindery** [comment]
Are there any plans for implementing this, is there a reason this has been open for so long or is it just about capacity/priority? Are you open to pull requests from somebody else implementing this? It's currently prohibiting us from using the TF provider.

**Comment by jianyuan** [comment]
> Are there any plans for implementing this, is there a reason this has been open for so long or is it just about capacity/priority? Are you open to pull requests from somebody else implementing this? It's currently prohibiting us from using the TF provider.

I plan to work on this this week. I aim to ship this by next week.

**Comment by isaacsanders** [comment]
I was just starting to define my team's Sentry resources and was pleased to see that this issue was being addressed. Thank you @jianyuan for your work on this! Let us know how we can help. Thank you for a very well documented provider.

**Comment by turingbeing** [comment]
Hi @jianyuan Like others have said here, we've just commenced defining teams via Terraform, and adding N+1 teams when creating a project would be great.

If there is anything I can do to help this along, please let me know.

**Comment by jianyuan** [comment]
This is now possible since [v0.10.0](https://github.com/jianyuan/terraform-provider-sentry/releases/tag/v0.10.0) 🎉
