### ISSUE TITLE
Internal Error PagerDuty Integration

### ISSUE THREAD

**Issue by akak548** [jianyuan/terraform-provider-sentry#87]
Getting random error when trying to rule the following rule with pagerduty integration. Running Terraform **0.14**

`Error: sentry: map[detail:Internal Error errorId:92d153b93ba24161bfa07c22e7db5c50]`

```
resource "sentry_rule" "pagerduty" {
  organization = "company
  project      = "test"
  action_match = "any"
  frequency    = "1d"
  name         = "PagerDuty rule"

  conditions =  [
      {
        id   = "sentry.rules.conditions.first_seen_event.FirstSeenEventCondition"
        name = "A new issue is created"
      },
      {
        id       = "sentry.rules.conditions.event_frequency.EventFrequencyCondition"
        value    = "1"
        interval = "1d"
      }
    ]

  filters = []

  actions = [
    {
      id      = "sentry.integrations.pagerduty.notify_action.PagerDutyNotifyServiceAction"
      account = [Retrieved from url of pagerduty integration. https://sentry.io/settings/coalition-inc/integrations/pagerduty/XXXX/]
      service = [Name of Service under pagerduty integration settings]
    }
  ]
}
```

**Comment by firthh** [comment]
I've got the same error. How did you solve this @akak548 ?

**Comment by firthh** [comment]
For anyone who finds their way here like I did. The solution is that `service` within the pagerduty action needs to be an `id`. You can find this ID by interrogating some JSON returned from the Sentry API (e.g. `https://sentry.io/api/0/organizations/{your-org-slug}/integrations/`). You will have multiple IDs are under `.configData.service_table` in the pagerduty integration for each pagerduty service
