### ISSUE TITLE
[Roadmap] what is the 2021 roadmap ?

### ISSUE THREAD

**Issue by semangard** [jianyuan/terraform-provider-sentry#89]
What is the 2021 roadmap ?
Do you plan to implement lots of new resources ?

**Comment by semangard** [comment]
@jianyuan : 
- do you plan to include users' management for ex as far as it is managed by your Go scripts ?
- do you plan to let a project been managed by multiple teams ?

**Comment by jianyuan** [comment]
Yes to all! Please watch this space.
