### ISSUE TITLE
Apple Silicon (darwin arm64) support

### ISSUE THREAD

**Issue by cablespaghetti** [jianyuan/terraform-provider-sentry#93]
Hi,

It would be great if you could build this for darwin_arm64 for compatbility with the latest Macs.

Thanks!

**Comment by Tenzer** [comment]
I think it should be pretty straightforward to do by following the guide here: https://learn.hashicorp.com/tutorials/terraform/provider-release-publish?in=terraform/providers. It sets up a workflow in GitHub Actions to build the binaries whenever a tag is created.

**Comment by arslanbekov** [comment]
If need `darwin_arm64` you can use this fork: https://github.com/anna-money/terraform-provider-sentry

**Comment by jgrau** [comment]
For the life of me I cannot change to `anna-money/sentry`. Changing the `required_providers` and `terraform init` still fetches `jianyuan/sentry` and fails with the `no package availabe for darwin_arm64` error message. I've tried removing the plugin cache and the entry from the lock file 🤔

**Comment by arslanbekov** [comment]
@jgrau did you manage to figure it out?
In my case i just delete `.terraform` folder and `.terraform.lock.hcl`, and after run `terraform init`

**Comment by jianyuan** [comment]
Hi all, there is now a darwin_arm64 build in v0.7.0 ([release page](https://github.com/jianyuan/terraform-provider-sentry/releases/tag/v0.7.0)).
