### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by antgel** [jianyuan/terraform-provider-sentry#96]
Looks like @jianyuan has gone AWOL, issues and PRs waiting for attention for months.

Meanwhile, Terraform and Sentry are a lethal combination and surely deserve a maintained module. What's the status?

**Comment by case** [comment]
Ideally, Sentry (the corp) would step up and make an actual, supported TF Provider here. Have you checked with them by any chance?

**Comment by antgel** [comment]
I have not, and I don't have any contacts there. I could open a support ticket, but I'm not optimistic.

**Comment by jianyuan** [comment]
Hey, apologies for the lack of updates as I've been busy with life. I'm looking to jump back into development in the coming days. Sentry recently reached out to me asking if I needed any resources. So we're working towards that. Watch this space.

**Comment by antgel** [comment]
Good news! It seems that there's a lot of interest. Look forward to hearing more on the subject.

**Comment by youcandanch** [comment]
@jianyuan if you need hands and have some items you want to break out, I'm happy to put some cycles in!

**Comment by ivanmartos** [comment]
@jianyuan feel free to also ping me if you will need some help

**Comment by antgel** [comment]
@jianyuan Hi, any news on "working towards that"? The issues and PRs are growing...

**Comment by arslanbekov** [comment]
We are actively using this provider in the company and had to fork it — https://github.com/anna-money/terraform-provider-sentry

In our fork, we have already added an assembly for `darwin_arm64` and rollback changes that [break the logic](https://github.com/anna-money/terraform-provider-sentry/commit/81e2a7812112b5f54aac232db8fc828fb4bc8155) `rule_resource`.

**Comment by jianyuan** [comment]
Happy to say the provider is back in active development 😄
